@startuml

entity "bo_phim" as bo_phim {
	* ma_bo_phim
	+ ten_bo_phim
	+ nam_phat_hanh
	+ the_loai
	+ so_tap
	+ so_diem_imdb
}

entity "dao_dien" as dao_dien {
	* ma_dao_dien
	+ ho_ten
	+ tuoi
	+ nam_tot_nghiep
	+ xep_hang
}

entity "dien_vien" as dien_vien {
	* ma_dien_vien
	+ ho_ten
	+ gioi_tinh
	+ tuoi
	+ so_vai_chinh
	+ so_vai_phu
}

entity "duoc_dien" as duoc_dien {
}

dao_dien |o--|{ bo_phim

bo_phim |o--|{ duoc_dien

dien_vien |o--|{ duoc_dien

@enduml