@startuml

entity "trang_phuc" as trang_phuc {
	* ma_trang_phuc
	+ ten_trang_phuc
	+ kich_co
	+ mau_sac
	+ gia_cho_thue
}

entity "khach_hang" as khach_hang {
	* ma_khach_hang
	+ ho_ten
	+ dia_chi
	+ so_dien_thoai
}

entity "hop_dong" as hop_dong {
	* ma_hop_dong
	+ ngay_bat_dau_hop_dong
	+ ngay_ket_thuc_hop_dong
	+ tri_gia_hop_dong
}

entity "thue" as thue {
}

khach_hang |o--|{ hop_dong

hop_dong |o--|{ thue

trang_phuc |o--|{ thue

@enduml